############################
# STEP 1 build executable binary
############################
FROM golang:alpine AS builder 
# Install git.
# Git is required for fetching the dependencies.
RUN apk update && apk add --no-cache git

RUN apk add build-base

WORKDIR $GOPATH/src/pay4me

COPY ./go.mod ./go.mod
COPY ./go.sum ./go.sum
COPY ./ ./

# Fetch dependencies.
RUN go mod download
RUN go mod verify

# Move generated
RUN mkdir -p ./ent/generated
RUN mv ./ent/_generated/generate.go ./ent/generated/generate.go

# Generate ent
RUN go run -mod=mod entgo.io/ent/cmd/ent generate --target ./ent/generated ./ent/schema 

# Build the binary.
RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/app ./server/server.go

############################
# STEP 2 build a small image
############################
FROM alpine

RUN apk update && apk add --no-cache ca-certificates
RUN apk upgrade --no-cache

# Copy our static executable.
COPY --from=builder /go/bin/app /go/bin/app

# Run the hello binary.
ENTRYPOINT ["/go/bin/app"]
