name: frame api
on:
    push:
        branches:
          - master
env:
    ENVIRONMENT: prod
    API_APP_PORT: ${{ vars.API_APP_PORT }}
    TUNNEL_TOKEN: ${{ vars.TUNNEL_TOKEN }}
jobs:
    prod_deploy:
        runs-on: [self-hosted, prod, frameapi]
        steps:
        -   uses: actions/checkout@v2
        -   name: check env
            env:
                API_APP_PORT: ${{ env.API_APP_PORT }}
            run: echo $API_APP_PORT
        # -   name: check var
        #     env:
        #         API_APP_PORT: ${{ vars.API_APP_PORT }}
        #     run: echo ${{ vars.API_APP_PORT }}
        # -   name: Validate config
        #     env:
        #         API_APP_PORT: ${{ env.API_APP_PORT }}
        #     run: echo $API_APP_PORT && docker compose -f ./deploy/docker-compose.yml config --quiet
        # -   name: Run build
        #     run: docker build -f ./deploy/dockerfile -t frameapi/frameapi:$GITHUB_SHA .
        # -   name: Check image
        #     run: docker images
        # -   name: Run app
        #     run: docker compose -f ./deploy/docker-compose.yml up -d
        # -   name: Wait and log app
        #     run: sleep 15 && docker compose -f ./deploy/docker-compose.yml logs --tail=20 api
        # -   name: Prune Docker system
        #     run: docker system prune -a -f
            